In [1]:
import os

In [2]:
print(os.listdir())

In [3]:
#import useful libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#get graphs inline
%matplotlib inline

In [4]:
#load up datafile
data = pd.read_csv('Social_Network_Ads.csv')

In [5]:
#check info about data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [6]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
#split our dataset
X = data.iloc[:,[2,3]].values
y = data.iloc[:, [4]].values

In [8]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [9]:
#split it into training and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
X_test

array([[    32, 117000],
       [    44, 139000],
       [    21,  88000],
       [    38,  65000],
       [    29,  83000],
       [    26,  16000],
       [    46,  79000],
       [    34,  43000],
       [    31,  66000],
       [    41,  45000],
       [    47,  34000],
       [    25,  87000],
       [    58, 144000],
       [    35,  59000],
       [    44,  39000],
       [    42, 108000],
       [    27,  58000],
       [    46,  28000],
       [    41,  80000],
       [    27,  88000],
       [    39,  42000],
       [    20,  86000],
       [    29,  83000],
       [    42,  65000],
       [    48,  33000],
       [    47,  43000],
       [    54,  70000],
       [    56, 104000],
       [    35,  71000],
       [    45,  22000],
       [    39, 134000],
       [    40,  60000],
       [    48, 119000],
       [    28,  85000],
       [    27,  90000],
       [    26,  17000],
       [    50,  36000],
       [    27,  54000],
       [    36,  75000],
       [    42,  90000],


In [11]:
#feature scalling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/Users/studio/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [12]:
#implement SVM
from sklearn.svm import SVC

In [13]:
classifier = SVC(kernel='linear')
classifier.fit(X_train, y_train.ravel())

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
#just predit
y_preditor = classifier.predict(X_test)

In [15]:
y_preditor

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [16]:
#consusion matix
from sklearn.metrics import confusion_matrix
errors = confusion_matrix(y_test, y_preditor)

In [17]:
errors

array([[52,  3],
       [ 9, 16]])