#Intermediate stuff with numpy

In [1]:
import numpy as np

In [2]:
myArray = np.arange(10,21)

In [3]:
myArray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
myArray[0]

10

In [5]:
myArray[1:4]

array([11, 12, 13])

In [6]:
myArray[:4]

array([10, 11, 12, 13])

In [7]:
myArray[4:]

array([14, 15, 16, 17, 18, 19, 20])

In [8]:
partArray = myArray[:4]

In [9]:
partArray

array([10, 11, 12, 13])

In [10]:
partArray[:] = 50

In [11]:
partArray

array([50, 50, 50, 50])

In [12]:
myArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

In [13]:
copyArray = myArray.copy()

In [15]:
copyArray[:] = 200

In [16]:
copyArray

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [17]:
myArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

In [18]:
myTwoDArray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [19]:
myTwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
myTwoDArray[2][1]

8

In [21]:
myTwoDArray[2,1]

8

In [22]:
myTwoDArray[2]

array([7, 8, 9])

In [23]:
myTwoDArray[:2, 1:]

array([[2, 3],
       [5, 6]])

In [24]:
newArray = np.arange(2, 20)

In [25]:
newArray

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [29]:
newArray[newArray < 10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
newArray > 10

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [35]:
np.sqrt(newArray)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894])