# Exercise file for Numpy


In [1]:
myList = [1,2,3,4,5]

In [2]:
myList

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [5]:
myOneDArray = np.array(myList)

In [6]:
myOneDArray

array([1, 2, 3, 4, 5])

In [7]:
myMultiList = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [9]:
myTwoDArray = np.array(myMultiList)

In [10]:
myTwoDArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

##get a matix of all 1s - 3,4

In [19]:
np.linspace(0,5, 15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [21]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5, 5)

array([[0.77610351, 0.90448222, 0.3678357 , 0.77796933, 0.24128707],
       [0.11049989, 0.5920898 , 0.53290426, 0.42469842, 0.68529288],
       [0.54911088, 0.25484866, 0.11564798, 0.41305858, 0.49920941],
       [0.52471668, 0.71645282, 0.34343404, 0.61664048, 0.99851121],
       [0.67707077, 0.47778479, 0.77024586, 0.18285755, 0.68485691]])

In [25]:
np.random.randn(5, 5)

array([[ 0.3843895 , -0.54172101,  0.53989909, -0.42859258,  0.32650343],
       [ 0.66551921, -0.16241867,  2.26250622,  0.93444825, -1.99106495],
       [ 0.14965492,  0.10100142,  1.17778668, -0.531357  , -0.09949317],
       [ 0.48320475, -0.16065598,  1.051609  , -1.26650082, -0.42361586],
       [-0.90569021,  0.84920891, -1.28676361,  0.01757787, -1.83964734]])

In [29]:
np.random.randint(1, 50)

23

In [30]:
myNum = np.arange(25)

In [31]:
myNum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
myReshaped = myNum.reshape(5,5)

In [33]:
myReshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])